# Generated by Django 5.1.2 on 2024-11-05 01:50

import apps.userauth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauth", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name_plural": "Users"},
        ),
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(
                default="path/to/default_image.jpg",
                upload_to=apps.userauth.models.user_directory_path,
            ),
        ),
    ]
