# Generated by Django 5.1.2 on 2024-11-05 01:50

import apps.userauth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauth", "0002_alter_user_options_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                default="", upload_to=apps.userauth.models.user_directory_path
            ),
        ),
    ]
