# Generated by Django 5.1.2 on 2024-11-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauth", "0004_user_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tipo_usuario",
            field=models.CharField(
                choices=[("S", "Staff"), ("V", "Vendedor"), ("C", "Cliente")],
                default="C",
                max_length=1,
            ),
        ),
    ]
