# Generated by Django 5.1.2 on 2024-11-10 17:40

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userauth", "0006_alter_user_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="uid",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="abc1234567", length=10, max_length=10, prefix="uid"
            ),
        ),
    ]
