# Generated by Django 5.1.2 on 2024-11-05 01:50

import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cId",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="abcdefgh1234567",
                        length=10,
                        max_length=20,
                        prefix="ctg",
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="categoria")),
            ],
            options={
                "verbose_name_plural": "Categorias",
            },
        ),
        migrations.CreateModel(
            name="Tags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pId",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="abcdefgh1234567",
                        length=10,
                        max_length=20,
                        prefix="prt",
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="produto")),
                ("descricao", models.TextField(blank=True, default="", null=True)),
                (
                    "preco",
                    models.DecimalField(
                        decimal_places=2, default="0.00", max_digits=9999999999999
                    ),
                ),
                (
                    "preco_antigo",
                    models.DecimalField(
                        decimal_places=2, default="0.00", max_digits=9999999999999
                    ),
                ),
                ("especificacao", models.TextField(blank=True, null=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.categoria",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tags",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.tags",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Produtos",
            },
        ),
    ]
