# Generated by Django 5.1.2 on 2024-11-05 16:32

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_produto_created_at_produto_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="cbr",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="1234567890", length=4, max_length=10, prefix="cbr"
            ),
        ),
    ]
