# Generated by Django 5.1.2 on 2024-11-05 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_produto_cbr"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produto",
            name="tags",
        ),
        migrations.DeleteModel(
            name="Tags",
        ),
    ]
