# Generated by Django 5.1.2 on 2024-11-05 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_tags_produto_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tags",
            options={"verbose_name_plural": "Tags"},
        ),
    ]
