# Generated by Django 5.1.2 on 2024-11-05 17:42

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_marca_rename_cid_categoria_cid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vendedor",
            name="imagem",
        ),
        migrations.AlterField(
            model_name="marca",
            name="imagem",
            field=models.ImageField(
                blank=True, null=True, upload_to=apps.core.models.marca_directory_path
            ),
        ),
        migrations.AlterField(
            model_name="produtosimagens",
            name="imagens",
            field=models.ImageField(
                blank=True, null=True, upload_to=apps.core.models.produt_directory_path
            ),
        ),
    ]
