# Generated by Django 5.1.2 on 2024-11-07 11:09

import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_vendedor_imagem_alter_marca_imagem_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PedidoVenda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pvid",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="abcdefgh1234567",
                        length=10,
                        max_length=20,
                        prefix="pv",
                        unique=True,
                    ),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=9999999999
                    ),
                ),
                ("pago", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "status_pedido",
                    models.CharField(
                        choices=[
                            (1, "Pendente"),
                            (2, "Processando"),
                            (3, "Aguardando Pagamento"),
                            (4, "Pagamento Realizado"),
                            (5, "Em Separação"),
                            (6, "Aguardando a Coleta"),
                            (7, "Em Transporte"),
                            (8, "Entregue"),
                            (9, "Finalizado"),
                            (0, "Cancelado"),
                        ],
                        default=1,
                        max_length=1,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Pedidos de Venda",
            },
        ),
        migrations.CreateModel(
            name="ItensPedidoVenda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item", models.CharField(max_length=7)),
                (
                    "qtd",
                    models.DecimalField(decimal_places=2, default=0, max_digits=999999),
                ),
                (
                    "status_produto",
                    models.CharField(
                        choices=[
                            (1, "Não Informado"),
                            (2, "Em Estoque"),
                            (3, "Sem Estoque"),
                            (4, "Em Producao"),
                            (5, "Fora de Linha"),
                        ],
                        default=1,
                        max_length=1,
                    ),
                ),
                (
                    "preco",
                    models.DecimalField(
                        decimal_places=2, default="0.00", max_digits=9999999999999
                    ),
                ),
                (
                    "preco_total",
                    models.DecimalField(
                        decimal_places=2, default="0.00", max_digits=9999999999999
                    ),
                ),
                (
                    "pvid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.pedidovenda",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Itens dos Pedidos de venda",
            },
        ),
    ]
