# Generated by Django 5.1.2 on 2024-11-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_itenspedidovenda_status_produto_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itenspedidovenda",
            name="item",
            field=models.CharField(default="0001", max_length=4),
        ),
    ]
