# Generated by Django 5.1.2 on 2024-11-07 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_itenspedidovenda_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="itenspedidovenda",
            name="produto",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.produto",
            ),
        ),
    ]
