# Generated by Django 5.1.2 on 2024-11-10 15:08

import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_itenspedidovenda_status_produto_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vendedor",
            name="nome",
        ),
        migrations.AddField(
            model_name="vendedor",
            name="cep",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="vendedor",
            name="cgc",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AddField(
            model_name="vendedor",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="vendedor",
            name="endereco",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="vendedor",
            name="estado",
            field=models.CharField(default="", max_length=2),
        ),
        migrations.AddField(
            model_name="vendedor",
            name="municipio",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="vendedor",
            name="nacional",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="vendedor",
            name="telefone",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="vendedor",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cid",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="abcdefgh1234567",
                        length=10,
                        max_length=20,
                        prefix="cli",
                        unique=True,
                    ),
                ),
                ("endereco", models.CharField(max_length=100)),
                ("cep", models.CharField(max_length=20)),
                ("municipio", models.CharField(max_length=100)),
                ("estado", models.CharField(max_length=2)),
                ("telefone", models.CharField(max_length=20)),
                ("nacional", models.BooleanField(default=True)),
                ("cgc", models.CharField(max_length=30)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.categoria"
                    ),
                ),
                (
                    "marcas",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.marca"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Clientes",
            },
        ),
        migrations.AddField(
            model_name="pedidovenda",
            name="cliente",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cliente",
                to="core.cliente",
            ),
        ),
        migrations.AddField(
            model_name="vendedor",
            name="clientes",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clientes",
                to="core.cliente",
            ),
        ),
    ]
