# Generated by Django 5.1.2 on 2024-11-10 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_remove_vendedor_nome_vendedor_cep_vendedor_cgc_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="itenspedidovenda",
            options={"verbose_name_plural": "Itens dos Pedido de venda"},
        ),
    ]
