# Generated by Django 5.1.2 on 2024-11-10 17:48

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_itenspedidovenda_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marca",
            name="mid",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="1234567890",
                length=4,
                max_length=10,
                prefix="mid",
                unique=True,
            ),
        ),
    ]
