# Generated by Django 5.1.2 on 2024-11-11 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alter_marca_mid"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProdutosImagens",
            new_name="ProdutoImagens",
        ),
    ]
