# Generated by Django 5.1.2 on 2024-11-11 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_rename_produtosimagens_produtoimagens"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cliente",
            name="categoria",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="marcas",
        ),
        migrations.RemoveField(
            model_name="produto",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="vendedor",
            name="clientes",
        ),
        migrations.RemoveField(
            model_name="vendedor",
            name="marcas",
        ),
        migrations.AddField(
            model_name="cliente",
            name="categoria",
            field=models.ManyToManyField(to="core.categoria"),
        ),
        migrations.AddField(
            model_name="cliente",
            name="marcas",
            field=models.ManyToManyField(to="core.marca"),
        ),
        migrations.AddField(
            model_name="produto",
            name="tags",
            field=models.ManyToManyField(null=True, to="core.tags"),
        ),
        migrations.AddField(
            model_name="vendedor",
            name="clientes",
            field=models.ManyToManyField(
                null=True, related_name="clientes", to="core.cliente"
            ),
        ),
        migrations.AddField(
            model_name="vendedor",
            name="marcas",
            field=models.ManyToManyField(null=True, to="core.marca"),
        ),
    ]
