# Generated by Django 5.1.2 on 2024-11-11 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_remove_cliente_categoria_remove_cliente_marcas_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="tags",
            field=models.ManyToManyField(to="core.tags"),
        ),
        migrations.AlterField(
            model_name="vendedor",
            name="clientes",
            field=models.ManyToManyField(related_name="clientes", to="core.cliente"),
        ),
        migrations.AlterField(
            model_name="vendedor",
            name="marcas",
            field=models.ManyToManyField(to="core.marca"),
        ),
    ]
