# Generated by Django 5.1.2 on 2024-11-21 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_alter_produto_tags_alter_vendedor_clientes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="produto"),
        ),
    ]
