# Generated by Django 5.1.2 on 2024-11-22 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_alter_produto_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itenspedidovenda",
            name="pvid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="itens",
                to="core.pedidovenda",
            ),
        ),
    ]
