# Generated by Django 5.1.2 on 2024-11-23 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_alter_itenspedidovenda_pvid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itenspedidovenda",
            name="produto",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="produto",
                to="core.produto",
            ),
        ),
        migrations.AlterField(
            model_name="itenspedidovenda",
            name="pvid",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="itens",
                to="core.pedidovenda",
            ),
        ),
        migrations.AlterField(
            model_name="produtoimagens",
            name="produto",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="produto_imagens",
                to="core.produto",
            ),
        ),
    ]
