# Generated by Django 5.1.2 on 2024-11-23 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_alter_itenspedidovenda_produto_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="produtoimagens",
            old_name="imagens",
            new_name="imagen",
        ),
    ]
