# Generated by Django 5.1.2 on 2024-12-29 18:30

import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_rename_imagens_produtoimagens_imagen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh1234567', length=10, max_length=20, prefix='cr', unique=True)),
                ('qtd', models.DecimalField(decimal_places=2, default=0, max_digits=999999)),
                ('created_at', models.DateField(auto_now=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartproduto', to='core.produto')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
