# Generated by Django 5.1.2 on 2024-12-29 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itenspedidovenda',
            name='produto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdvproduto', to='core.produto'),
        ),
    ]
